/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2023-09-18 11:14:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class docente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1695035568427L));
    _jspx_dependants.put("jar:file:/C:/Users/rodolfo%20alberto/Desktop/Proyecto%20a%20subir%20github/Lenguaje%20de%20Programacion%20c4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/aplicacion/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098729090000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	if(session.getAttribute("listaMenus")==null)
		response.sendRedirect("login.jsp?MENSAJE=debe iniciar sesión");

      out.write("\r\n");
      out.write("<!-- incluir página menu.jsp -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- trabajar con la libreria core de jstl -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t<!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"css/dataTables.bootstrap5.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<title>Mantenimiento Docente</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t.modal-header{\r\n");
      out.write("\t\tcolor:#fff;\r\n");
      out.write("\t\tbackground: #428bca;\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("  \t\tjustify-content: center;\r\n");
      out.write("  \t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.help-block {\r\n");
      out.write("\t  \t\tcolor: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t.form-group.has-error .form-control-label {\r\n");
      out.write("\t  color: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t.form-group.has-error .form-control {\r\n");
      out.write("\t  border: 1px solid red;\r\n");
      out.write("\t  box-shadow: 0 0 0 0.2rem rgba(250, 16, 0, 0.18);\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t  <h2 class=\"text-center mt-3\">LISTADO DE DOCENTES</h2>\r\n");
      out.write("\t  <button type=\"button\" class=\"btn btn-primary mt-3\" data-bs-toggle=\"modal\" data-bs-target=\"#modalDocente\">\r\n");
      out.write("\t  \tNuevo Docente\r\n");
      out.write("\t  </button>\r\n");
      out.write("\t  <!-- Modal -->\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"modalDocente\" data-bs-backdrop=\"static\" data-bs-keyboard=\"false\" tabindex=\"-1\" aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t  <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t      <div class=\"modal-header\">\r\n");
      out.write("\t\t        <h5 class=\"modal-title\" id=\"staticBackdropLabel\">Docente</h5>\r\n");
      out.write("\t\t        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t        <form id=\"frmDocente\" action=\"ServletDocente?tipo=GRABAR\" method=\"post\">\r\n");
      out.write("\t\t          <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"nombres\" class=\"form-label\">Código</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" name=\"codigo\" value=\"0\" id=\"id-codigo\" readonly>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"nombres\" class=\"form-label\">Nombres</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" name=\"nombres\" id=\"id-nombre\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"paterno\" class=\"form-label\">Paterno</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" name=\"paterno\" id=\"id-paterno\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"materno\" class=\"form-label\">Materno</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" name=\"materno\" id=\"id-materno\">\r\n");
      out.write("\t\t\t\t  </div>\t\t\t\t  \r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"sueldo\" class=\"form-label\">Sueldo</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" name=\"sueldo\" id=\"id-sueldo\">\r\n");
      out.write("\t\t\t\t  </div>\t\t\t\t  \r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"hijos\" class=\"form-label\">Hijos</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" name=\"hijos\"id=\"id-hijos\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"sexo\" class=\"form-label\">Sexo</label>\r\n");
      out.write("\t\t\t\t    <select class=\"form-select form-control\" name=\"sexo\" id=\"id-sexo\">\r\n");
      out.write("\t\t\t\t\t  <option value=\"\" selected>[Seleccione Sexo]</option>\r\n");
      out.write("\t\t\t\t\t  <option value=\"Femenino\">Femenino</option>\r\n");
      out.write("\t\t\t\t\t  <option value=\"Masculino\">Masculino</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label for=\"condicion\" class=\"form-label\">Condición</label>\r\n");
      out.write("\t\t\t\t    <select class=\"form-select form-control\" name=\"condicion\" id=\"id-condicion\">\r\n");
      out.write("\t\t\t\t\t  <option value=\"\" selected>[Seleccione Condición]</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t  </div>\t\t\t\t  \r\n");
      out.write("\t\t\t\t  \t\t\t\t  \t\t\t\t  \r\n");
      out.write("\t\t\t\t  <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t  \t<button type=\"submit\" class=\"btn btn-primary\">Grabar</button>\r\n");
      out.write("\t\t\t        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cerrar</button>\r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  <!-- FIN MODAL -->\r\n");
      out.write("\t  \r\n");
      out.write("\t  <!-- Modal Eliminar-->\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"modalEliminar\" data-bs-backdrop=\"static\" data-bs-keyboard=\"false\" tabindex=\"-1\" aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t  <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t      <div class=\"modal-header\">\r\n");
      out.write("\t\t        <h5 class=\"modal-title\" id=\"staticBackdropLabel\">Sistema</h5>\r\n");
      out.write("\t\t        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t      \t<h4>Seguro de eliminar?</h4>\r\n");
      out.write("\t\t        <form id=\"frmDocente\" action=\"ServletDocente?tipo=ELIMINAR\" method=\"post\">\r\n");
      out.write("\t\t\t\t    <input type=\"hidden\" name=\"codigoEliminar\" id=\"id-codigo-eliminar\">\t  \r\n");
      out.write("\t\t\t\t  <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t  \t<button type=\"submit\" class=\"btn btn-primary\">SI</button>\r\n");
      out.write("\t\t\t        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">NO</button>\r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  <!-- FIN MODAL Eliminar-->\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  <div class=\"mt-5\">\r\n");
      out.write("\t\t  <table id=\"tableDocente\" class=\"table table-striped\" style=\"width:100%\">\r\n");
      out.write("\t        <thead>\r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t                <th>CÓDIGO</th>\r\n");
      out.write("\t                <th>NOMBRE</th>\r\n");
      out.write("\t                <th>PATERNO</th>\r\n");
      out.write("\t                <th>MATERNO</th>\r\n");
      out.write("\t                <th>SEXO</th>\r\n");
      out.write("\t                <th>HIJOS</th>\r\n");
      out.write("\t                <th>SUELDO</th>\r\n");
      out.write("\t                <th></th>\r\n");
      out.write("\t                <th></th>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t        </thead>\r\n");
      out.write("\t        <tbody>\r\n");
      out.write("\t\t        <!--abrir la etiqueta forEach  \r\n");
      out.write("\t\t        atributo items,sirve para almacenar el atributo que viene del Servlet\r\n");
      out.write("\t\t        atributo var, sirve para crear un objeto que almacene el valor actual según la vuelta del for\r\n");
      out.write("\t\t        -->\r\n");
      out.write("\t\t            \r\n");
      out.write("\r\n");
      out.write("\t        </tbody>\r\n");
      out.write("\t    </table>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t</div>\r\n");
      out.write("<script src=\"js/jquery-3.5.1.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<!-- Option 1: Bootstrap Bundle with Popper -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- JS para la tabla -->\r\n");
      out.write("<script src=\"https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- JS para la validación-->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-validator/0.4.0/js/bootstrapValidator.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tleerCondicionJSON();\r\n");
      out.write("\tleerDocenteJSON();\r\n");
      out.write("\t\r\n");
      out.write("\t//asignar evento click a todos los botones con nombre de clase \"btn-editar\"\r\n");
      out.write("\t//JQUERY\r\n");
      out.write("\t$(document).on(\"click\",\".btn-editar\",function(){\r\n");
      out.write("\t\t//variables\r\n");
      out.write("\t\tlet cod,nom,pat,mat,sexo,hijos,sue;\r\n");
      out.write("\t\t//leer columnas de la fila donde se hizo click en el botón editar\r\n");
      out.write("\t\tcod=$(this).parents(\"tr\").find(\"td\")[0].innerHTML;\r\n");
      out.write("\t\t$.get(\"ServletDocentePorID?codigo=\"+cod,function(response){\r\n");
      out.write("\t\t\tconsole.log(response);\r\n");
      out.write("\t\t\tdocument.querySelector(\"#id-codigo\").value=response.codigo;\r\n");
      out.write("\t\t\tdocument.querySelector(\"#id-nombre\").value=response.nombre;\r\n");
      out.write("\t\t\tdocument.querySelector(\"#id-paterno\").value=response.paterno;\r\n");
      out.write("\t\t\tdocument.querySelector(\"#id-materno\").value=response.materno;\r\n");
      out.write("\t\t\tdocument.querySelector(\"#id-sexo\").value=response.sexo;\r\n");
      out.write("\t\t\tdocument.querySelector(\"#id-hijos\").value=response.hijos;\r\n");
      out.write("\t\t\tdocument.querySelector(\"#id-sueldo\").value=response.sueldo;\r\n");
      out.write("\t\t\tdocument.querySelector(\"#id-condicion\").value=response.codigoCondicion;\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\tnom=$(this).parents(\"tr\").find(\"td\")[1].innerHTML;\r\n");
      out.write("\t\tpat=$(this).parents(\"tr\").find(\"td\")[2].innerHTML;\r\n");
      out.write("\t\tmat=$(this).parents(\"tr\").find(\"td\")[3].innerHTML;\r\n");
      out.write("\t\tsexo=$(this).parents(\"tr\").find(\"td\")[4].innerHTML;\r\n");
      out.write("\t\thijos=$(this).parents(\"tr\").find(\"td\")[5].innerHTML;\r\n");
      out.write("\t\tsue=$(this).parents(\"tr\").find(\"td\")[6].innerHTML;\r\n");
      out.write("\t\t*/\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t//asignar evento click a todos los botones con nombre de clase \"btn-eliminar\"\r\n");
      out.write("\t//JQUERY\r\n");
      out.write("\t$(document).on(\"click\",\".btn-eliminar\",function(){\r\n");
      out.write("\t\t//variable\r\n");
      out.write("\t\tlet cod;\r\n");
      out.write("\t\t//leer columna(còdigo) de la fila donde se hizo click en el botón eliminar\r\n");
      out.write("\t\tcod=$(this).parents(\"tr\").find(\"td\")[0].innerHTML;\r\n");
      out.write("\t\tdocument.querySelector(\"#id-codigo-eliminar\").value=cod;\r\n");
      out.write("\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t//función para leer json\r\n");
      out.write("\tfunction leerCondicionJSON(){\r\n");
      out.write("\t\t//funcion JQUERY\r\n");
      out.write("\t\t$.get(\"ServletCondicionJSON\",function(response){\r\n");
      out.write("\t\t\t//imprimir consola del navegador\r\n");
      out.write("\t\t\t//console.log(response);\r\n");
      out.write("\t\t\t//bucle\r\n");
      out.write("\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t$(\"#id-condicion\").append(\"<option value='\"+item.codigo+\"'>\"+item.nombre+\"</option>\");\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction leerDocenteJSON(){\r\n");
      out.write("\t\t$.get(\"ServletDocente?tipo=LISTARJSON\",function(response){\r\n");
      out.write("\t\t\tconsole.log(response);\r\n");
      out.write("\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t$(\"#tableDocente\").append(\"<tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"<td>\"+item.codigo+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\titem.nombre+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\titem.paterno+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\titem.materno+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\titem.sexo+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\titem.hijos+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\titem.sueldo+\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"<td><button type='button' class='btn btn-success btn-editar' data-bs-toggle='modal' data-bs-target='#modalDocente'>Editar</button></td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"<td><button type='button' class='btn btn-danger btn-eliminar' data-bs-toggle='modal' data-bs-target='#modalEliminar'>Eliminar</button></td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"</tr>\");\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t$('#tableDocente').DataTable();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<script>    \r\n");
      out.write("    $(document).ready(function(){     \r\n");
      out.write("        $('#frmDocente').bootstrapValidator({      \r\n");
      out.write("        \t fields:{\r\n");
      out.write("        \t\t nombres:{\r\n");
      out.write("        \t\t\t validators:{\r\n");
      out.write("        \t\t\t\t notEmpty:{\r\n");
      out.write("        \t\t\t\t\t message:'Campo nombres es obligatorio'\r\n");
      out.write("        \t\t\t\t },\r\n");
      out.write("        \t\t\t\t regexp:{\r\n");
      out.write("        \t\t\t\t\t regexp:/^[a-zA-Z\\ñ\\Ñ\\s\\á\\é\\í\\ó\\ú\\Á\\É\\Í\\Ó\\Ú]{2,20}$/,\r\n");
      out.write("        \t\t\t\t\t message:'Campo nombres solo letras MIN:3 - MAX:20'\r\n");
      out.write("        \t\t\t\t }\r\n");
      out.write("        \t\t\t }\r\n");
      out.write("        \t\t },\r\n");
      out.write("        \t\t paterno:{\r\n");
      out.write("        \t\t\t validators:{\r\n");
      out.write("        \t\t\t\t notEmpty:{\r\n");
      out.write("        \t\t\t\t\t message:'Campo paterno es obligatorio'\r\n");
      out.write("        \t\t\t\t },\r\n");
      out.write("        \t\t\t\t regexp:{\r\n");
      out.write("        \t\t\t\t\t regexp:/^[a-zA-Z\\ñ\\Ñ\\s\\á\\é\\í\\ó\\ú\\Á\\É\\Í\\Ó\\Ú]{4,25}$/,\r\n");
      out.write("        \t\t\t\t\t message:'Campo paterno solo letras MIN:4 - MAX:25'\r\n");
      out.write("        \t\t\t\t }\r\n");
      out.write("        \t\t\t }\r\n");
      out.write("        \t\t },\r\n");
      out.write("        \t\t materno:{\r\n");
      out.write("        \t\t\t validators:{\r\n");
      out.write("        \t\t\t\t notEmpty:{\r\n");
      out.write("        \t\t\t\t\t message:'Campo materno es obligatorio'\r\n");
      out.write("        \t\t\t\t },\r\n");
      out.write("        \t\t\t\t regexp:{\r\n");
      out.write("        \t\t\t\t\t regexp:/^[a-zA-Z\\ñ\\Ñ\\s\\á\\é\\í\\ó\\ú\\Á\\É\\Í\\Ó\\Ú]{4,25}$/,\r\n");
      out.write("        \t\t\t\t\t message:'Campo paterno solo letras MIN:4 - MAX:25'\r\n");
      out.write("        \t\t\t\t }\r\n");
      out.write("        \t\t\t }\r\n");
      out.write("        \t\t },\r\n");
      out.write("        \t\t sueldo:{\r\n");
      out.write("        \t\t\t validators:{\r\n");
      out.write("        \t\t\t\t notEmpty:{\r\n");
      out.write("        \t\t\t\t\t message:'Campo sueldo es obligatorio'\r\n");
      out.write("        \t\t\t\t }\r\n");
      out.write("        \t\t\t }\r\n");
      out.write("        \t\t }, \r\n");
      out.write("        \t\t hijos:{\r\n");
      out.write("        \t\t\t validators:{\r\n");
      out.write("        \t\t\t\t notEmpty:{\r\n");
      out.write("        \t\t\t\t\t message:'Campo hijos es obligatorio'\r\n");
      out.write("        \t\t\t\t },\r\n");
      out.write("        \t\t\t\t regexp:{\r\n");
      out.write("        \t\t\t\t\t regexp:/^([0-9]|[1][0-2])$/,\r\n");
      out.write("        \t\t\t\t\t message:'Campo hijos MIN:0 - MAX:12'\r\n");
      out.write("        \t\t\t\t }\r\n");
      out.write("        \t\t\t }\r\n");
      out.write("        \t\t },\r\n");
      out.write("        \t\t sexo:{\r\n");
      out.write("        \t\t\t validators:{\r\n");
      out.write("        \t\t\t\t notEmpty:{\r\n");
      out.write("        \t\t\t\t\t message:'Campo sexo es obligatorio'\r\n");
      out.write("        \t\t\t\t }\r\n");
      out.write("        \t\t\t }\r\n");
      out.write("        \t\t },\r\n");
      out.write("        \t\t condicion:{\r\n");
      out.write("        \t\t\t validators:{\r\n");
      out.write("        \t\t\t\t notEmpty:{\r\n");
      out.write("        \t\t\t\t\t message:'Campo condición es obligatorio'\r\n");
      out.write("        \t\t\t\t }\r\n");
      out.write("        \t\t\t }\r\n");
      out.write("        \t\t },\r\n");
      out.write("        \t\t \r\n");
      out.write("        \t }\r\n");
      out.write("        });   \r\n");
      out.write("\t\t\t\r\n");
      out.write("    });    \r\n");
      out.write("</script>   \t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /docente.jsp(44,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.MENSAJE!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\t\r\n");
          out.write("\t\t\t<div class=\"alert alert-warning alert-dismissible fade show\" role=\"alert\">\r\n");
          out.write("\t\t\t  <strong>Sistema : </strong> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.MENSAJE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("\t\t\t  <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
