/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2023-09-18 11:14:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1695035568427L));
    _jspx_dependants.put("jar:file:/C:/Users/rodolfo%20alberto/Desktop/Proyecto%20a%20subir%20github/Lenguaje%20de%20Programacion%20c4/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/aplicacion/WEB-INF/lib/standard.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1098729090000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"ISO-8859-1\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <title>Intranet</title>\n");
      out.write("  <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body {\n");
      out.write("  background: #eee;\n");
      out.write("}\n");
      out.write(".wrapper {\n");
      out.write("  margin: 15%;\n");
      out.write("}\n");
      out.write(".form-signin {\n");
      out.write("  max-width: 380px;\n");
      out.write("  margin: 0 auto;\n");
      out.write("  background-color: #fff;\n");
      out.write("  padding: 5px 40px 50px;\n");
      out.write("  border: 1px solid #e5e5e5;\n");
      out.write("  border-radius: 10px;\n");
      out.write("}\n");
      out.write(".form-signin .form-signin-heading, .form-signin .checkbox {\n");
      out.write("  margin-bottom: 30px;\n");
      out.write("}\n");
      out.write(".form-signin input[type=\"text\"], .form-signin input[type=\"password\"] {\n");
      out.write("  margin-bottom: 20px;\n");
      out.write("}\n");
      out.write(".form-signin .form-control {\n");
      out.write("  padding: 10px;\n");
      out.write("}\n");
      out.write(".modal-login {\n");
      out.write("\t\tcolor: #636363;\n");
      out.write("\t\t/*width: 350px;*/\n");
      out.write("\t\tmargin: 25px auto;\n");
      out.write("\t}\n");
      out.write("\t.modal-login .modal-content {\n");
      out.write("\t\tpadding: 0px;\n");
      out.write("\t\tborder-radius: 5px;\n");
      out.write("\t\tborder: none;\n");
      out.write("\t}\n");
      out.write("\t.modal-login .modal-header {\n");
      out.write("\t\tborder-bottom: none;\n");
      out.write("\t\tposition: relative;\n");
      out.write("\t\tjustify-content: center;\n");
      out.write("\t}\n");
      out.write("\t.modal-login h4 {\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tfont-size: 26px;\n");
      out.write("\t}\n");
      out.write("\t.modal-login  .form-group {\n");
      out.write("\t\tposition: relative;\n");
      out.write("\t}\n");
      out.write("\t.modal-login i {\n");
      out.write("\t\tposition: absolute;\n");
      out.write("\t\tleft: 13px;\n");
      out.write("\t\ttop: 11px;\n");
      out.write("\t\tfont-size: 18px;\n");
      out.write("\t}\n");
      out.write("\t.modal-login .form-control {\n");
      out.write("\t\tpadding-left: 40px;\n");
      out.write("\t}\n");
      out.write("\t.modal-login .form-control:focus {\n");
      out.write("\t\tborder-color: #428bca;\n");
      out.write("\t}\n");
      out.write("\t.modal-login .form-control, .modal-login .btn {\n");
      out.write("\t\tmin-height: 40px;\n");
      out.write("\t\tborder-radius: 3px; \n");
      out.write("\t}\n");
      out.write("\t.modal-login .hint-text {\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tpadding-top: 10px;\n");
      out.write("\t}\n");
      out.write("\t.modal-login .close {\n");
      out.write("        position: absolute;\n");
      out.write("\t\ttop: -5px;\n");
      out.write("\t\tright: -5px;\n");
      out.write("\t}\n");
      out.write("\t.modal-login .btn {\n");
      out.write("\t\tbackground: #428bca;\n");
      out.write("\t\tborder: none;\n");
      out.write("\t\tline-height: normal;\n");
      out.write("\t\tfont-weight:bold;\n");
      out.write("\t\twidth:40%;\n");
      out.write("\t}\n");
      out.write("\t.modal-login .btn:hover, .modal-login .btn:focus {\n");
      out.write("\t\tbackground: #428bca;\n");
      out.write("\t}\n");
      out.write("\t.modal-login .modal-footer {\n");
      out.write("\t\tbackground: #ecf0f1;\n");
      out.write("\t\tborder-color: #dee4e7;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tmargin: 0 -20px -20px;\n");
      out.write("\t\tborder-radius: 5px;\n");
      out.write("\t\tfont-size: 13px;\n");
      out.write("\t\tjustify-content: center;\n");
      out.write("\t}\n");
      out.write("\t.modal-login .modal-footer a {\n");
      out.write("\t\tcolor: #999;\n");
      out.write("\t}\n");
      out.write("\t.trigger-btn {\n");
      out.write("\t\tdisplay: inline-block;\n");
      out.write("\t\tmargin: 100px auto;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.modal-header{\n");
      out.write("\t\tmargin:0px;\n");
      out.write("\t\tcolor:#fff;\n");
      out.write("\t\tbackground: #428bca;\n");
      out.write("\t\tdisplay: flex;\n");
      out.write("  \t\tjustify-content: center;\n");
      out.write("  \t\t\n");
      out.write("\t}\n");
      out.write("\t.pie{\n");
      out.write("\t\tmargin:0px;\n");
      out.write("\t\tdisplay: flex;\n");
      out.write("  \t\tjustify-content: center;\n");
      out.write("  \t\t\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"wrapper\">\n");
      out.write("<div id=\"myModal\">\n");
      out.write("\t<div class=\"modal-dialog modal-login\">\n");
      out.write("\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t<div class=\"modal-header\">\t\t\t\t\n");
      out.write("\t\t\t\t<h5 class=\"modal-title\">INGRESAR INTRANET</h5>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t<form action=\"ServletUsuario?accion=INICIAR\" method=\"post\">\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-user\"></i>\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Username\" required=\"required\" name=\"login\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-lock\"></i>\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" placeholder=\"Password\" required=\"required\" name=\"clave\">\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"pie\">\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-primary btn-sm\" aria-pressed=\"true\"value=\"Iniciar Sesión\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</form>\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>     \n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"js/jquery-3.5.1.js\"></script>\n");
      out.write("\t\n");
      out.write("<!-- Option 1: Bootstrap Bundle with Popper -->\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /login.jsp(150,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.MENSAJE!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\t\n");
          out.write("\t\t\t\t<div class=\"alert alert-warning alert-dismissible fade show\" role=\"alert\">\n");
          out.write("\t\t\t\t  <strong>Sistema : </strong> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.MENSAJE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("\t\t\t\t  <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\n");
          out.write("\t\t\t\t</div>\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
